Setup mobile
ilyassatlassi/portfolio_setup_mobile pull request #2
Opened 2022-10-27 11:46 UTC by ilyassatlassi

2022-10-27 12:00 UTC, jerryowusu reviewed
Hi @ilyassatlassi 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![invalid](https://user-images.githubusercontent.com/65233860/198278692-9f24feef-6f9a-44d0-8b32-729714e19de5.png)


## Invalid Code Review Request

You have submitted a Pull request with no descriptive and detailed summary/description as shown below. Kindly fix that.

![Screenshot from 2022-10-27 11-52-30](https://user-images.githubusercontent.com/65233860/198278621-dea86c53-8482-4013-bd5d-faf8fc94cc64.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-27 12:14 UTC, ilyassatlassi commented
@jerryowusu how i can add a description to my pull request

2022-10-27 12:36 UTC, jerryowusu commented
> @jerryowusu how i can add a description to my pull request

in the image below where it is written `illyatlassi commented .....`, kindly track it on the pull request page, click on the three dots on the far right, you will see the option to edit in the pop up that appears

2022-10-27 13:21 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @ilyassatlassi , I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

- [ ] You did a great job in your design it looks nice but there is some points you need to work on. you must stick to the design as much as possible (e.g. font, colors, images, text, margins) as was required in the project. using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] [OPTIONAL] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-10-27 13:21 UTC, MaganaAsiati commented on style.css
> +}
- You did a great job by aligning correctly your hamburger menu and your logo but kindly make sure the core you use this color  `color: #6070FF;` provide in the Figma design and reduce a bit the font size of your hamburger so 
that it will make your header section design stick to the Figma design as it was required in the project. :+1:  :sunglasses: 

## Your design 
![image](https://user-images.githubusercontent.com/95297251/198293164-3f903901-4f47-4910-bde6-4c858b4af8ad.png)



## Figma design 

![image](https://user-images.githubusercontent.com/95297251/198253129-a4610909-9a89-49ae-95a7-57d269045e79.png)

2022-10-27 22:03 UTC, ilyassatlassi commented on index.html
> +            </div>
@MaganaAsiati when i try to change he doesn't work with me

2022-10-28 09:40 UTC, BertrandConxy requested changes
Hi @ilyassatlassi, 

Great work on making the changes requested by a previous reviewer 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 💪 
- No linter errors
- correct flow is used
- good improvement based on the previous reviewer's suggestions
- good PR


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 09:40 UTC, BertrandConxy commented on README.md
> +
- [ ] As suggested by the previous reviewer, please add a brief description of your project. This helps others know what your project do 😃

2022-10-28 09:40 UTC, BertrandConxy commented on README.md
> +
- [ ] The previous reviewer suggested that you remove the unnecessary comments in the `Getting started` section but you removed the whole section. It is important to note that this section is among the important ones in the README file therefore, It should not miss there. Please add the `Getting started` section and add a procedure to clone your project and run it locally. You can refer to [this one](https://github.com/BertrandConxy/Space-Travellers-Hub/blob/dev-branch/README.md)

2022-10-28 10:59 UTC, ilyassatlassi commented on README.md
> +
@BertrandConxy can you give me please more details

2022-10-29 17:16 UTC, bienvenuushindi commented on README.md
> +
@BertrandConxy This section of your README file tells what your project is about.
For instance: This is my portfolio website, which was created using HTML and CSS in accordance with this Figma design.

2022-10-29 17:19 UTC, bienvenuushindi approved these changes
# STATUS: APPROVED 🟢 

## Hi @ilyassatlassi    👋, 

Well done implementing the requested changes 👏
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/lJNoBCvQYp7nq/giphy.gif"/>

### Highlights 🎯 
:+1: No linter errors✔️
:+1: Good PR title

### Optional Suggestions

 Nothing to say

**_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 17:30 UTC, merged